; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 32MB
#board_build.partitions = default_16MB.csv
build_flags =
    -DBOARD_HAS_PSRAM               # enable PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1     # reroute USB CDC to UART0 (required for serial monitor over USB)
    -mfix-esp32-psram-cache-issue   # fix PSRAM cache issue (no idea what this does but it works)
    -fexceptions                    # enable C++ exceptions
    -std=gnu++17                    # use C++17
board_build.arduino.memory_type = opi_opi # use the OPI memory layout
monitor_speed = 115200 # set the serial monitor speed to 115200 baud
